<Project Sdk="Microsoft.NET.Sdk">


    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
        <PackageReference Include="AspNetCore.HealthChecks.Redis" />
        <PackageReference Include="StackExchange.Redis" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CoreLibs.Cache\CoreLibs.Cache.csproj" />
    </ItemGroup>

</Project>
