<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Quartz" />
        <PackageReference Include="Quartz.Extensions.DependencyInjection" />
        <PackageReference Include="Quartz.Extensions.Hosting" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options" />
        <PackageReference Include="OpenTelemetry.Api" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DenisCuciuc.Platform.Jobs\DenisCuciuc.Platform.Jobs.csproj" />
    </ItemGroup>

</Project>
