<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Configuration\DenisCuciuc.Platform.Configuration.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.CQRS\DenisCuciuc.Platform.CQRS.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Domain\DenisCuciuc.Platform.Domain.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.ErrorHandling\DenisCuciuc.Platform.ErrorHandling.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.HealthCheck\DenisCuciuc.Platform.HealthCheck.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Metrics\DenisCuciuc.Platform.Metrics.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Postgres\DenisCuciuc.Platform.Postgres.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Postgres.Startup\DenisCuciuc.Platform.Postgres.Startup.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Sentry\DenisCuciuc.Platform.Sentry.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Serilog\DenisCuciuc.Platform.Serilog.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Startup\DenisCuciuc.Platform.Startup.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Swagger\DenisCuciuc.Platform.Swagger.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Swagger.Theme\DenisCuciuc.Platform.Swagger.Theme.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Data\Migrations\" />
    </ItemGroup>

</Project>
