<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Configuration\DenisCuciuc.Platform.Configuration.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.CQRS\DenisCuciuc.Platform.CQRS.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Domain\DenisCuciuc.Platform.Domain.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.ErrorHandling\DenisCuciuc.Platform.ErrorHandling.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.HealthCheck\DenisCuciuc.Platform.HealthCheck.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Metrics\DenisCuciuc.Platform.Metrics.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.MongoDB\DenisCuciuc.Platform.MongoDB.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.MongoDB.Startup\DenisCuciuc.Platform.MongoDB.Startup.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Redis\DenisCuciuc.Platform.Redis.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Redis.Startup\DenisCuciuc.Platform.Redis.Startup.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Sentry\DenisCuciuc.Platform.Sentry.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Serilog\DenisCuciuc.Platform.Serilog.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Startup\DenisCuciuc.Platform.Startup.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Swagger\DenisCuciuc.Platform.Swagger.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Swagger.Theme\DenisCuciuc.Platform.Swagger.Theme.csproj" />
    </ItemGroup>

</Project>
