<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Configuration\DenisCuciuc.Platform.Configuration.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.HealthCheck\DenisCuciuc.Platform.HealthCheck.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Jobs\DenisCuciuc.Platform.Jobs.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Jobs.Hangfire\DenisCuciuc.Platform.Jobs.Hangfire.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Jobs.Hangfire.MongoDB\DenisCuciuc.Platform.Jobs.Hangfire.MongoDB.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Jobs.Startup\DenisCuciuc.Platform.Jobs.Startup.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Metrics\DenisCuciuc.Platform.Metrics.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Serilog\DenisCuciuc.Platform.Serilog.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Startup\DenisCuciuc.Platform.Startup.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Swagger\DenisCuciuc.Platform.Swagger.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Swagger.Theme\DenisCuciuc.Platform.Swagger.Theme.csproj" />
    </ItemGroup>

</Project>
