<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Quartz.Serialization.SystemTextJson" />
        <PackageReference Include="Npgsql" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DenisCuciuc.Platform.Jobs.Quartz\DenisCuciuc.Platform.Jobs.Quartz.csproj" />
    </ItemGroup>

</Project>
