<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <!-- OpenTelemetry.Exporter.Prometheus.AspNetCore has no stable release yet -->
      <NoWarn>$(NoWarn);NU5104</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AspNetCore.HealthChecks.Prometheus.Metrics" />
      <PackageReference Include="AspNetCore.HealthChecks.Publisher.Prometheus" />
      <PackageReference Include="OpenTelemetry" />
      <PackageReference Include="OpenTelemetry.Api" />
      <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
      <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
      <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
      <PackageReference Include="prometheus-net.AspNetCore" />
    </ItemGroup>

</Project>
