<Project Sdk="Microsoft.NET.Sdk">


    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Swashbuckle.AspNetCore.Swagger"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI"/>
    </ItemGroup>

</Project>
