<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="coverlet.collector"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\CoreLibs.LiveConfig\CoreLibs.LiveConfig.csproj"/>
        <ProjectReference Include="..\..\src\CoreLibs.LiveConfig.GSheet\CoreLibs.LiveConfig.GSheet.csproj"/>
        <ProjectReference Include="..\..\src\CoreLibs.LiveConfig.Json\CoreLibs.LiveConfig.Json.csproj"/>
        <ProjectReference Include="..\..\src\CoreLibs.LiveConfig.Startup\CoreLibs.LiveConfig.Startup.csproj"/>
    </ItemGroup>

</Project>
