<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Hangfire.Core" />
        <PackageReference Include="Hangfire.InMemory" />
        <PackageReference Include="Hangfire.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Api" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DenisCuciuc.Platform.Jobs\DenisCuciuc.Platform.Jobs.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
