<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp" />
        <PackageReference Include="Testcontainers.Redis" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="coverlet.collector" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Redis\DenisCuciuc.Platform.Redis.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Redis.Startup\DenisCuciuc.Platform.Redis.Startup.csproj" />
        <ProjectReference Include="..\..\src\DenisCuciuc.Platform.Cache\DenisCuciuc.Platform.Cache.csproj" />
    </ItemGroup>

</Project>
