services:
  mongodb:
    image: mongo:7
    container_name: localization-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: localization_example
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: localization-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16-alpine
    container_name: localization-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: localization_example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  redis_data:
  postgres_data:
